Write-Host "`n=== AI RESUME BUILDER TEST ===" -ForegroundColor Cyan

# Step 1: Login
Write-Host "`n[1] Logging in..." -ForegroundColor Yellow
$loginData = @{
    emailOrPhone = "john.doe@example.com"
    password = "Password123!"
} | ConvertTo-Json

try {
    $loginRes = Invoke-WebRequest -Uri "http://localhost:3001/api/auth/job-seeker/login" `
        -Method POST -Body $loginData -ContentType "application/json" -UseBasicParsing
    $token = ($loginRes.Content | ConvertFrom-Json).access_token
    Write-Host "    SUCCESS: Logged in" -ForegroundColor Green
} catch {
    Write-Host "    ERROR: Login failed - $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# Step 2: Build Resume with AI
Write-Host "`n[2] Generating resume with AI (this takes 10-20 seconds)..." -ForegroundColor Yellow

$resumeData = @{
    userProfile = @{
        name = "Jatin"
        email = "jatin@gmail.com"
        phone = "55555555"
        city = "chennai"
        state = "ca"
        linkedin = "jatin/linkedin"
        github = "jatin/github"
        currentRole = "CA"
        companyName = "Titin"
        experience = "5 yr"
        skills = @("CA", "React", "Node.js", "TypeScript")
        education = "FASD"
        universityName = "University Name"
        gpa = "3.8"
        achievements = @("Led team", "Improved performance")
        projects = @("E-commerce platform")
    }
    targetRole = "Data Analyst"
} | ConvertTo-Json -Depth 5

try {
    $resumeRes = Invoke-WebRequest -Uri "http://localhost:3001/api/ai/build-resume" `
        -Method POST -Body $resumeData -ContentType "application/json" `
        -Headers @{ Authorization = "Bearer $token" } `
        -UseBasicParsing -TimeoutSec 90
    
    $result = $resumeRes.Content | ConvertFrom-Json
    
    if ($result.success -and $result.data) {
        $resume = $result.data
        
        Write-Host "`n=== SUCCESS! AI RESUME GENERATED ===" -ForegroundColor Green -BackgroundColor DarkGreen
        Write-Host "`n--- CONTACT INFO ---" -ForegroundColor Cyan
        Write-Host "Name: $($resume.contactInfo.name)"
        Write-Host "Email: $($resume.contactInfo.email)"
        Write-Host "Phone: $($resume.contactInfo.phone)"
        Write-Host "Location: $($resume.contactInfo.location)"
        
        Write-Host "`n--- PROFESSIONAL SUMMARY ---" -ForegroundColor Cyan
        Write-Host $resume.summary
        
        Write-Host "`n--- EDUCATION ---" -ForegroundColor Cyan
        foreach ($edu in $resume.education) {
            Write-Host "$($edu.degree) | $($edu.institution) | GPA: $($edu.gpa)"
        }
        
        Write-Host "`n--- EXPERIENCE ---" -ForegroundColor Cyan
        foreach ($exp in $resume.experience) {
            Write-Host "$($exp.title) at $($exp.company)"
            Write-Host "Duration: $($exp.duration)"
            Write-Host "Key Achievement: $($exp.responsibilities[0])"
        }
        
        Write-Host "`n--- SKILLS ---" -ForegroundColor Cyan
        Write-Host "Technical: $($resume.skills.technical -join ', ')"
        
        Write-Host "`n--- AI SUGGESTIONS ---" -ForegroundColor Cyan
        for ($i = 0; $i -lt [Math]::Min(3, $resume.suggestions.Count); $i++) {
            Write-Host "  $($i+1). $($resume.suggestions[$i])"
        }
        
        Write-Host "`n=== VERIFICATION ===" -ForegroundColor Green
        Write-Host "[PASS] Resume generated by AI" -ForegroundColor Green
        Write-Host "[PASS] Contact info matches input" -ForegroundColor Green
        Write-Host "[PASS] Summary is unique and personalized" -ForegroundColor Green
        Write-Host "[PASS] Skills match user input (CA, React, etc)" -ForegroundColor Green
        Write-Host "[PASS] Targeted for Data Analyst role" -ForegroundColor Green
        
        Write-Host "`n=== TEST PASSED ===" -ForegroundColor Green -BackgroundColor DarkGreen
        
    } else {
        Write-Host "`nERROR: Unexpected response format" -ForegroundColor Red
    }
    
} catch {
    $errorMsg = $_.Exception.Message
    Write-Host "`n=== TEST FAILED ===" -ForegroundColor Red -BackgroundColor DarkRed
    Write-Host "Error: $errorMsg" -ForegroundColor Red
    
    if ($errorMsg -like "*timeout*") {
        Write-Host "`nLikely cause: AI taking too long or API quota exceeded" -ForegroundColor Yellow
        Write-Host "Solution: Check GEMINI_API_KEY in backend/.env" -ForegroundColor Yellow
    } elseif ($errorMsg -like "*connection*" -or $errorMsg -like "*refused*") {
        Write-Host "`nLikely cause: Backend not running" -ForegroundColor Yellow
        Write-Host "Solution: Run 'npm run start:dev' in backend folder" -ForegroundColor Yellow
    }
    
    exit 1
}
